config/routes.rb
Rails.application.routes.draw do
  resources :flashcards
  root 'static_pages#index'
  get 'user_home' => 'flashcards#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users

end

app/models/flashcard.rb
class Flashcard < ActiveRecord::Base
  belongs_to :user
  validates :front, presence: true
  validates :back, presence: true
  validates :user_id, presence: true
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :set_flashcard, only: [:show, :edit, :update, :destroy]

  # GET /flashcards
  # GET /flashcards.json
  def index
    @flashcards = current_user.flashcards.all
  end

  # GET /flashcards/1
  # GET /flashcards/1.json
  def show
    @flashcard = current_user.flashcards.find(params[:id])
  end

  # GET /flashcards/new
  def new
    @flashcard = current_user.flashcards.new
  end

  # GET /flashcards/1/edit
  def edit
  end

  # POST /flashcards
  # POST /flashcards.json
  def create
    @flashcard = current_user.flashcards.new(flashcard_params)

    respond_to do |format|
      if @flashcard.save
        format.html { redirect_to @flashcard, notice: 'flashcard was successfully created.' }
        format.json { render :show, status: :created, location: @flashcard }
      else
        format.html { render :new }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flashcards/1
  # PATCH/PUT /flashcards/1.json
  def update
    respond_to do |format|
      if @flashcard.update(flashcard_params)
        format.html { redirect_to @flashcard, notice: 'flashcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @flashcard }
      else
        format.html { render :edit }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashcards/1
  # DELETE /flashcards/1.json
  def destroy
    @flashcard.destroy
    respond_to do |format|
      format.html { redirect_to flashcards_url, notice: 'flashcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flashcard
      @flashcard = Flashcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flashcard_params
      params.require(:flashcard).permit(:front, :back)
    end
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/views/flashcards/_flashcard.html.erb
<li id="flashcard-<%=flashcard.id%>">
  <span class="user"><%= link_to flashcard.user.name, flashcard.user %></span>
  <span class="front">flashcard.front</span>
  <span class="back">flashcard.back</span>
</li>

app/views/flashcards/_form.html.erb
<%= form_for(@flashcard) do |f| %>
<div class="col-md-6 col-md-offset-3">
<%= f.label :front, 'back' %><br>
  <%= f.text_field :front, class: 'form-control' %>
  
  <%= f.label :back, 'back' %><br>
  <%= f.text_field :back, class: 'form-control' %>
  
  <%= f.submit 'update flashcard', class: 'btn btn-default' %></div>
  <% end %>

app/views/flashcards/edit.html.erb
<%= provide(:title, "edit") %>
<h1>edit</h1>

<%= render 'form' %>

<div class="showlinksgi"><%= link_to 'Show', @flashcard %> |
  <%= link_to 'Back', flashcards_path %></div>

app/views/flashcards/index.html.erb
<%= provide(:title, "card index") %>
<!-- <p id="notice"><%= notice %></p>-->
<h1 class="center">my flashcards</h1>
<!-- <h4 class="center">a list of created flashcards</h4> -->
<div class="container-fluid">
  <table class="flashcard-table">
    <thead>
      <tr>
        <th><div class="flashcard-head">Front</div></th>
        <th><div class="flashcard-head">Back </div></th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @flashcards.each do |flashcard| %>
      <tr>
        <td><div class="colwrapper">
          <div class="flashcard-summary"><%= flashcard.front %></div>
        </div></td>
        <td><div class="colwrapper"><div class="flashcard-summary"><%= flashcard.back %></div> </div></td>
        <td><%= link_to 'Show', flashcard %></td>
        <td><%= link_to 'Edit', edit_flashcard_path(flashcard) %></td>
        <td><%= link_to 'Destroy', flashcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<!-- <br> -->
</div>
<div class="flashcard-create">
  <%= link_to 'New Flashcard', new_flashcard_path %>
</div>

app/views/flashcards/new.html.erb
<%= provide(:title, "new card") %>
<h1> new card</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
    <%= form_for(@flashcard) do |f| %>
    <%= f.label :front %>
    <%= f.text_field :front, class: 'form-control'%>
    
    <%= f.label :back %>
    <%= f.text_field :back, class: 'form-control'%>
    <%= f.submit "create card", class: "btn btn-default" %>
    <% end %>
  </div>
</div>
<div class="newflashspacer"></div>
<div class="backlink"><%= link_to 'Back', flashcards_path %></div>

app/views/flashcards/show.html.erb
<%= provide(:title, "show cards") %>
<!-- <p id="notice"><%= notice %></p> -->
<div class="row">
  <div class="col-md-6 front-show center"><p>
  <strong>Front:</strong>
  <br>
  <%= @flashcard.front %>
</p>
<div class="flashspacer"></div>
</div>
<div class="col-md-6 back-show center"><p>
  <strong>Back:</strong>
  <br>
  <%= @flashcard.back %>
</p></div>
<div class="flashspacer"></div>
</div>



<div class="showlinks">
  <%= link_to 'Edit', edit_flashcard_path(@flashcard) %> |
  <%= link_to 'Back', flashcards_path %>
  </div>