config/routes.rb
Rails.application.routes.draw do
  resources :flashcards
  root 'static_pages#index'
  get 'user_home' => 'flashcards#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users

end

app/views/layouts/_footer.html.erb
<footer>
  <ul class="rfooter">
    <li><%= link_to "about", about_path %></li>
    <li><%= link_to "contact", contact_path %></li>
  </ul>
  <ul class="lfooter">
    <li>
      a minimal flashcard app <%=link_to "fergusbarratt.me", 'http://fergusbarratt.me'%>

    </li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="nav navbar-fixed-top">
    <div class="logo"><%= link_to "flash", root_path %></div>
    <nav>
      <ul class="rheader">
          <% if logged_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "all users", users_path %></li>
            <% end %>
            <li><%= link_to 'my flashcards', flashcards_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "profile", current_user %></li>
                <li><%= link_to "settings", edit_user_path(current_user) %></li>
                <li>
                <%= link_to "logout", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "login", login_path %></li>
          <% end %>
      </ul>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="container-fluid flash"> 
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="header"><%= render 'layouts/header' %></div>
    <div class="content"> <%= yield %>   
      <div class="clearfooter">
</div>
    </div>
        <!-- <div class="debug_dump"><%= debug(params) if Rails.env.development? %></div> -->
    <div class="footer"> <%= render 'layouts/footer' %> </div>
  </div>  
</body>
</html>